<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>

<?php
/**
 * CLI template
 *
 * @var $block \Magefan\Cli\Block\Adminhtml\Form
 * @var $mfSecureRenderer \Magefan\Community\Api\SecureHtmlRendererInterface
 *
 * @codingStandardsIgnoreStart
 */
$exec = $block->execExist();
$magentoCommands = $block->getMagentoCommands();
$url = $block->getUrl('adminhtml/system_config/edit', ['section' => 'mfcli']);
$script = '';
?>

<?php if (!$block->isModuleEnabled()) {?>
    <div class="messages">
        <div class="message message-error error">
            <div data-ui-id="messages-message-error">
                <?= $block->escapeHtml(__(strrev(' ot etagivan esaelp noisnetxe eht elbane ot ,delbasid si ecafretnI eniL dnammoC nafegaM'))) ?><a href="<?= $block->escapeUrl($url) ?>" target="_blank"><?= $block->escapeHtml(__(strrev('ecafretnI eniL dnammoC > snoisnetxE nafegaM > noitarugifnoC > serotS'))) ?></a>
            </div>
        </div>
    </div>
<?php } elseif (!count(array_filter($magentoCommands))) { ?>
    <div class="messages">
        <div class="message message-error error">
            <div data-ui-id="messages-message-error">
                <?= $block->escapeHtml(__('There are no allowed commands to execute for the current user.')) ?>
            </div>
        </div>
    </div>
<?php } else {?>
    <?php
    $mostUsed = $magentoCommands['most_used'];
    $commands = $magentoCommands['commands'];
    ?>
    <style>
        #shell-area{float:left;width:78%;margin:0;list-style:none;background:#141414;color:#45D40C;font:.8em 'Andale Mono',Consolas,'Courier New';line-height:1.6em;padding:10px; min-height:500px;max-height:500px;overflow-y: auto;}
        #shell-area input{width:80%; background: #141414;border:none;padding:10px;line-height:15px}
        #command-list ul{float:right;height:200px;width:20%;min-height:500px;max-height:500px;}
        #command-list ul{overflow:hidden;overflow-y:scroll;overflow-x:scroll;}
        #command-list li {padding-bottom: 10px}
        #command-list li .execute {padding-left: 10px}

        .row:after {content:'';display:table;clear:both;}
        .execute, .execute-label {cursor: pointer;}
    </style>

    <div class="admin__scope-old">
        <div class="entry-edit form-inline">
            <div class="ui-tabs-panel ui-widget-content ui-corner-bottom" >
                <div class="entry-edit form-inline">
                    <fieldset class="fieldset admin__fieldset ">
                        <legend class="admin__legend legend">
                            <span><?php echo $block->escapeHtml(__('Current User Identity Verification')) ?></span>
                        </legend>
                        <br>
                        <div class="messages">
                        </div>
                        <div class="admin__field field field-current_password  required _required" >
                            <label class="label admin__field-label" for="user_current_password"><span><?php echo $block->escapeHtml(__('Your Password')) ?></span></label>
                            <div class="admin__field-control control">
                                <input id="user_current_password" name="current_password" value="" title="<?php echo $block->escapeHtml(__('Your Password')) ?>" class="input-text " type="password" >
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div id="shell-area">
            <div class="history-hld"></div>
            <div class="input-hld">
                <?php if ($exec) { ?>
                    <?php echo $block->escapeHtml(__('Enter Command:')) ?><input id="command" />
                <?php } else { ?>
                    <?php echo $block->escapeHtml(__('This command line is not accessible. Exec function is not allowed in PHP settings. Please use the standard CLI interface.')) ?>
                <?php } ?>
            </div>
        </div>
        <div id="command-list">
            <ul>
                <?php if (count($mostUsed)) { ?>
                    <p><?= $block->escapeHtml(__('Most Used Commands')) ?></p>
                    <?php foreach ($mostUsed as $command) { ?>
                        <?php if ($command) { ?>
                            <li>
                                <span class="execute-label"><?= $block->escapeHtml($command) ?></span>
                                <span class="execute" title="<?= $block->escapeHtml('Execute') ?>" data-name="<?= $block->escapeHtml($command) ?>">▶</span>
                            </li>
                        <?php } ?>
                    <?php } ?>
                    <br><hr><br>
                <?php } ?>
                <?php foreach ($commands as $command) { ?>
                    <?php if ($command) { ?>
                        <li>
                            <span class="execute-label"><?= $block->escapeHtml($command) ?></span>
                            <span class="execute"  title="<?= $block->escapeHtml('Execute') ?>" data-name="<?= $block->escapeHtml($command) ?>">▶</span>
                        </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>
    </div>

    <?php if ($exec) { ?>

        <?php $script .= "
        	require(['jquery', 'Magento_Ui/js/modal/confirm'], function($, confirmation) {
		$(function(){
			$('#shell-area').click(function(){
				$('#command').focus();
			})
		});

		var commandLog = [];
		var commandLogIndex = 0;
		function showCommand()
		{
			var i = commandLog.length - 1 - commandLogIndex;
			// console.log(i);
			if (typeof commandLog[i] !== 'undefined') {
				$('#command').val(commandLog[i])
			} else {
				$('#command').val('');
			}
		}

		function addCommand()
		{
			var el = $('#command');
			v = $.trim(el.val());
			if (v) {
				commandLog.push(v);
			}
			var commandLogIndex = 0;
			el.val('');
		}

		function addContent(c)
		{
			addCommand();
			$('.history-hld').append(c);
			$('#shell-area').scrollTop($('#shell-area')[0].scrollHeight);
		}

		var loading = false;
        $('#command').keydown(function(event) {
            var el = $(this);
            if(event.which == 40) { //up
                event.preventDefault();
                commandLogIndex--;
                if (commandLogIndex < 0) {
                    commandLogIndex = 0;
                }
                showCommand();
            } else if(event.which == 38) { //down
                event.preventDefault();
                showCommand();
                commandLogIndex++;
                if (commandLogIndex >= commandLog.length) {
                    commandLogIndex = commandLog.length-1;
                }
            } else if(event.which == 13) { //enter
                event.preventDefault();
                if (loading) return;
                loading = true;

		    	if (!$.trim(el.val())) {
		    		addContent('<br/>');
		    		loading = false;
		    		return;
		    	}

		        $.ajax({
                    url: '" . $block->escapeUrl($block->getUrl('*/*/cli')) . "',
                    data : {command:el.val(),current_password:$('#user_current_password').val(),form_key:$('input[name=\"form_key\"]').val()},
                    type: 'POST',
                    dataType: 'json',
                    showLoader: true
                }).done(function (data) {
                    loading = false;
                    if (data && data.message) {
                        addContent('<strong>$ </strong>' + el.val() + '<br/>');
                        addContent(data.message);
                    } else {
                        alert('" . $block->escapeHtml(__('Unexpected error. Please refresh the page or try later.')) . "');
                    }
                    if (data && data.newFormKey) {
                        $('input[name=\"form_key\"]').val(data.newFormKey);
                    }
                });
		    }
		});

        $('.execute-label').click(function() {
            var command = 'bin/magento ' + $(this).closest('li').find('.execute').attr('data-name');
            $('#command').val(command).focus();
        });

        $('.execute').click(function() {
            var command = 'bin/magento ' + $(this).closest('li').find('.execute').attr('data-name');
            $('#command').val(command).focus();

            confirmation({
                title: $.mage.__('Execute Command:') + ' ' + command,
                content: $.mage.__('Are you sure you want to do this?'),
                actions: {
                    confirm: function() {

                        $.ajax({
                            url: '" . $block->escapeUrl($block->getUrl('*/*/cli')) . "',
                            data: {
                                command: 'php ' + command,
                                current_password: $('#user_current_password').val(),
                                form_key: $('input[name=\"form_key\"]').val()
                            },
                            type: 'POST',
                            dataType: 'json',
                            showLoader: true
                        }).done(function (data) {

                            if (data && data.message) {
                                addContent('<strong>$ </strong>' + command + '<br/>');
                                addContent(data.message);
                            } else {
                                alert('" . $block->escapeHtml(__('Unexpected error. Please refresh the page or try later.')) . "');
                            }

                            if (data && data.newFormKey) {
                                FORM_KEY = data.newFormKey;
                                $('input[name=\"form_key\"]').val(FORM_KEY);
                            }
                        });
                    },
                    cancel: function() {}
                }
            });
        });
	});
    "; ?>

        <?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
    <?php } ?>
<?php } ?>